use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde_json::Value;

const BANG_LEAF_KEY: &str = "\u{10}";
const BANG_RANK_SEP: char = '\u{1}';

fn literal(value: &str) -> String {
    format!("{value:?}")
}

fn optional_literal(value: Option<&str>) -> String {
    value.map_or_else(
        || "None".to_string(),
        |value| format!("Some({})", literal(value)),
    )
}

fn string_slice(values: impl IntoIterator<Item = String>) -> String {
    let values = values
        .into_iter()
        .map(|value| literal(&value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("&[{values}]")
}

fn flatten_bang_trie(node: &Value, prefix: &str, output: &mut BTreeMap<String, (String, i32)>) {
    match node {
        Value::String(definition) => {
            let mut parts = definition.splitn(2, BANG_RANK_SEP);
            let url = parts.next().unwrap_or_default().to_string();
            let rank = parts
                .next()
                .and_then(|rank| rank.parse().ok())
                .unwrap_or_default();
            output.insert(prefix.to_string(), (url, rank));
        }
        Value::Object(children) => {
            for (key, value) in children {
                if key == BANG_LEAF_KEY {
                    if let Value::String(definition) = value {
                        let mut parts = definition.splitn(2, BANG_RANK_SEP);
                        let url = parts.next().unwrap_or_default().to_string();
                        let rank = parts
                            .next()
                            .and_then(|rank| rank.parse().ok())
                            .unwrap_or_default();
                        output.insert(prefix.to_string(), (url, rank));
                    }
                } else {
                    flatten_bang_trie(value, &format!("{prefix}{key}"), output);
                }
            }
        }
        _ => {}
    }
}

fn json_value_expression(value: &Value) -> String {
    match value {
        Value::Null => "serde_json::Value::Null".to_string(),
        Value::Bool(value) => format!("serde_json::Value::Bool({value})"),
        Value::Number(value) => format!(
            "serde_json::Value::Number({}.parse().expect(\"generated JSON number\"))",
            literal(&value.to_string())
        ),
        Value::String(value) => {
            format!("serde_json::Value::String({}.to_string())", literal(value))
        }
        Value::Array(values) => format!(
            "serde_json::Value::Array(vec![{}])",
            values
                .iter()
                .map(json_value_expression)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Value::Object(values) => format!(
            "serde_json::Value::Object([{}].into_iter().collect())",
            values
                .iter()
                .map(|(key, value)| format!(
                    "({}.to_string(), {})",
                    literal(key),
                    json_value_expression(value)
                ))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn main() {
    let data_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir")).join("data");
    for file in [
        "external_bangs.json",
        "currencies.json",
        "wikidata_units.json",
        "engine_traits.json",
        "locales.json",
        "useragents.json",
        "gsa_useragents.txt",
        "tracker_patterns.json",
        "ahmia_blacklist.txt",
    ] {
        println!("cargo:rerun-if-changed={}", data_dir.join(file).display());
    }

    let read_json = |file: &str| -> Value {
        serde_json::from_str(
            &fs::read_to_string(data_dir.join(file)).expect("read bundled data file"),
        )
        .expect("parse bundled data JSON")
    };

    let mut generated = String::from("// @generated by build.rs; do not edit.\n");

    let mut bangs = BTreeMap::new();
    flatten_bang_trie(&read_json("external_bangs.json")["trie"], "", &mut bangs);
    let mut bang_map = phf_codegen::Map::new();
    let bang_entries: Vec<(String, String)> = bangs
        .iter()
        .map(|(token, (url, rank))| (token.clone(), format!("({}, {})", literal(url), rank)))
        .collect();
    for (token, entry) in &bang_entries {
        bang_map.entry(token, entry);
    }
    generated.push_str(&format!(
        "pub static PRECOMPILED_BANGS: phf::Map<&'static str, (&'static str, i32)> = {};\n",
        bang_map.build()
    ));

    let currencies = read_json("currencies.json");
    generated.push_str("pub static PRECOMPILED_CURRENCY_NAMES: &[(&str, &[&str])] = &[\n");
    for (name, codes) in currencies["names"].as_object().expect("currency names") {
        let values = match codes {
            Value::String(code) => vec![code.clone()],
            Value::Array(codes) => codes
                .iter()
                .map(|code| code.as_str().expect("currency code").to_string())
                .collect(),
            _ => panic!("invalid currency name"),
        };
        generated.push_str(&format!("({}, {}),\n", literal(name), string_slice(values)));
    }
    generated
        .push_str("];\npub static PRECOMPILED_CURRENCY_ISO: &[(&str, &[(&str, &str)])] = &[\n");
    for (code, languages) in currencies["iso4217"].as_object().expect("currency iso") {
        let entries = languages
            .as_object()
            .expect("currency languages")
            .iter()
            .map(|(language, name)| {
                format!(
                    "({}, {})",
                    literal(language),
                    literal(name.as_str().expect("currency display name"))
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        generated.push_str(&format!("({}, &[{}]),\n", literal(code), entries));
    }
    generated.push_str("];\n");

    let units = read_json("wikidata_units.json");
    generated.push_str(
        "pub static PRECOMPILED_UNITS: &[(&str, Option<&str>, &str, Option<f64>)] = &[\n",
    );
    for (id, unit) in units.as_object().expect("units") {
        generated.push_str(&format!(
            "({}, {}, {}, {:?}),\n",
            literal(id),
            optional_literal(unit["si_name"].as_str()),
            literal(unit["symbol"].as_str().expect("unit symbol")),
            unit["to_si_factor"].as_f64()
        ));
    }
    generated.push_str("];\n");

    let traits = read_json("engine_traits.json");
    generated.push_str("pub static PRECOMPILED_ENGINE_TRAITS: &[(&str, Option<&str>, Option<&str>, &[(&str, &str)], &[(&str, &str)])] = &[\n");
    for (engine, trait_value) in traits.as_object().expect("engine traits") {
        let pairs = |name: &str| {
            trait_value[name]
                .as_object()
                .map(|map| {
                    map.iter()
                        .map(|(key, value)| {
                            format!(
                                "({}, {})",
                                literal(key),
                                literal(value.as_str().expect("trait value"))
                            )
                        })
                        .collect::<Vec<_>>()
                        .join(", ")
                })
                .unwrap_or_default()
        };
        generated.push_str(&format!(
            "({}, {}, {}, &[{}], &[{}]),\n",
            literal(engine),
            optional_literal(trait_value["all_locale"].as_str()),
            optional_literal(trait_value["data_type"].as_str()),
            pairs("languages"),
            pairs("regions"),
        ));
    }
    generated.push_str("];\n");
    generated
        .push_str("pub fn precompiled_engine_trait_custom() -> Vec<serde_json::Value> { vec![\n");
    for trait_value in traits.as_object().expect("engine traits").values() {
        generated.push_str(&format!(
            "{},\n",
            json_value_expression(&trait_value["custom"])
        ));
    }
    generated.push_str("] }\n");

    let locales = read_json("locales.json");
    generated.push_str("pub static PRECOMPILED_LOCALE_NAMES: &[(&str, &str)] = &[\n");
    for (locale, name) in locales["LOCALE_NAMES"].as_object().expect("locale names") {
        generated.push_str(&format!(
            "({}, {}),\n",
            literal(locale),
            literal(name.as_str().expect("locale name"))
        ));
    }
    generated.push_str("];\n");
    generated.push_str(&format!(
        "pub static PRECOMPILED_RTL_LOCALES: &[&str] = {};\n",
        string_slice(
            locales["RTL_LOCALES"]
                .as_array()
                .expect("rtl locales")
                .iter()
                .map(|locale| locale.as_str().expect("rtl locale").to_string())
        )
    ));

    let useragents = read_json("useragents.json");
    generated.push_str(&format!(
        "pub static PRECOMPILED_USERAGENT_OS: &[&str] = {};\npub static PRECOMPILED_USERAGENT_TEMPLATE: &str = {};\npub static PRECOMPILED_USERAGENT_VERSIONS: &[&str] = {};\n",
        string_slice(useragents["os"].as_array().expect("useragent os").iter().map(|value| value.as_str().expect("os").to_string())),
        literal(useragents["ua"].as_str().expect("useragent template")),
        string_slice(useragents["versions"].as_array().expect("useragent versions").iter().map(|value| value.as_str().expect("version").to_string())),
    ));
    let gsa = fs::read_to_string(data_dir.join("gsa_useragents.txt")).expect("read gsa useragents");
    generated.push_str(&format!(
        "pub static PRECOMPILED_GSA_USERAGENTS: &[&str] = {};\n",
        string_slice(
            gsa.lines()
                .map(str::trim)
                .filter(|line| !line.is_empty())
                .map(str::to_string)
        )
    ));

    let trackers = read_json("tracker_patterns.json");
    generated
        .push_str("pub static PRECOMPILED_TRACKER_PATTERNS: &[(&str, &[&str], &[&str])] = &[\n");
    for tracker in trackers.as_array().expect("tracker patterns") {
        let strings = |name: &str| {
            string_slice(
                tracker[name]
                    .as_array()
                    .into_iter()
                    .flatten()
                    .map(|value| value.as_str().expect("tracker pattern").to_string()),
            )
        };
        generated.push_str(&format!(
            "({}, {}, {}),\n",
            literal(tracker["url"].as_str().expect("tracker url")),
            strings("exceptions"),
            strings("rules"),
        ));
    }
    generated.push_str("];\n");

    let output = PathBuf::from(env::var("OUT_DIR").expect("out dir")).join("generated_data.rs");
    fs::write(output, generated).expect("write generated data");
}
