//! Native Zoeken search API (`/api/v1/search`).

pub mod schema;
pub mod serialize;

pub use schema::{
    NATIVE_SCHEMA_VERSION, NativeAnswer, NativeCorrection, NativeInfobox, NativeInteractiveAnswer,
    NativeResult, NativeSearchRequest, NativeSearchResponse, NativeSuggestion,
    NativeUnresponsiveEngine,
};
pub use serialize::NativeMapContext;

use zoeken_query::FormParams;

impl NativeSearchRequest {
    pub fn to_form_params(&self) -> FormParams {
        let mut pairs = Vec::new();
        pairs.push(("q".to_string(), self.q.clone()));
        pairs.push(("pageno".to_string(), self.pageno.max(1).to_string()));
        if let Some(language) = &self.language {
            pairs.push(("language".to_string(), language.clone()));
        }
        if let Some(safesearch) = self.safesearch {
            pairs.push(("safesearch".to_string(), safesearch.to_string()));
        }
        if let Some(categories) = &self.categories {
            pairs.push(("categories".to_string(), categories.clone()));
        }
        if let Some(time_range) = &self.time_range {
            pairs.push(("time_range".to_string(), time_range.clone()));
        }
        if let Some(engines) = &self.engines {
            pairs.push(("engines".to_string(), engines.clone()));
        }
        FormParams::from_pairs(pairs)
    }
}

/// Render TypeScript bindings for committed SPA codegen.
pub fn export_typescript() -> String {
    use ts_rs::TS;

    let mut out = String::from(
        "// @generated by export-native-ts — do not edit\n\
         /* eslint-disable */\n\
         // biome-ignore-all lint: generated\n\n",
    );
    for decl in [
        NativeSearchRequest::decl(),
        NativeSearchResponse::decl(),
        NativeResult::decl(),
        NativeAnswer::decl(),
        NativeInteractiveAnswer::decl(),
        NativeCorrection::decl(),
        NativeSuggestion::decl(),
        NativeInfobox::decl(),
        schema::NativeInfoboxUrl::decl(),
        schema::NativeInfoboxImage::decl(),
        schema::NativeInfoboxAttribute::decl(),
        NativeUnresponsiveEngine::decl(),
    ] {
        out.push_str("export ");
        out.push_str(&decl);
        out.push_str("\n\n");
    }
    out
}
